### ISSUE TITLE
ChunkLoadError in /tracks/julia

### ISSUE THREAD

**Issue by iHiD** [exercism/website#2022]
## Error in v3 (client side)

**ChunkLoadError** in **/tracks/julia**
Loading chunk 5 failed.
(timeout: https://exercism-v3-assets.s3.eu-west-2.amazonaws.com/packs/js/5-0e3ae9d73229343f034c.chunk.js)

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/61590aacf8918000076bac05?event_id=61590aac0082d5c9421e0000&i=gh&m=ci)

## Stacktrace

    app/javascript/packs/application.tsx:236 - 

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/61590aacf8918000076bac05?event_id=61590aac0082d5c9421e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SleeplessByte** [comment]
Almost always happens if you've updated the webpacker resources and deployed, but no longer have the previous chunks available (because you replace the entire deployment stack). The chunks would then, rightfully, no longer be available.

You can either resolve this by trying to catch this and issue a full page reload, but usually people will do this themselves.

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ChunkLoadError** in **/dashboard**](https://app.bugsnag.com/exercism/v3-client-side/errors/61590aacf8918000076bac05?event_id=615c68850083c746c9b30000&i=gh&m=fx)
